#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTQLAV
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="QL_TTANHNGU")]
	public partial class QL_TTANHNGUDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertChiNhanh(ChiNhanh instance);
    partial void UpdateChiNhanh(ChiNhanh instance);
    partial void DeleteChiNhanh(ChiNhanh instance);
    partial void InsertChiTiet_CaDay(ChiTiet_CaDay instance);
    partial void UpdateChiTiet_CaDay(ChiTiet_CaDay instance);
    partial void DeleteChiTiet_CaDay(ChiTiet_CaDay instance);
    partial void InsertChiTietDK_LH(ChiTietDK_LH instance);
    partial void UpdateChiTietDK_LH(ChiTietDK_LH instance);
    partial void DeleteChiTietDK_LH(ChiTietDK_LH instance);
    partial void InsertChiTietDK_TT(ChiTietDK_TT instance);
    partial void UpdateChiTietDK_TT(ChiTietDK_TT instance);
    partial void DeleteChiTietDK_TT(ChiTietDK_TT instance);
    partial void InsertCongViec(CongViec instance);
    partial void UpdateCongViec(CongViec instance);
    partial void DeleteCongViec(CongViec instance);
    partial void InsertGiangVien(GiangVien instance);
    partial void UpdateGiangVien(GiangVien instance);
    partial void DeleteGiangVien(GiangVien instance);
    partial void InsertHoaDon(HoaDon instance);
    partial void UpdateHoaDon(HoaDon instance);
    partial void DeleteHoaDon(HoaDon instance);
    partial void InsertHocVien(HocVien instance);
    partial void UpdateHocVien(HocVien instance);
    partial void DeleteHocVien(HocVien instance);
    partial void InsertKetQua(KetQua instance);
    partial void UpdateKetQua(KetQua instance);
    partial void DeleteKetQua(KetQua instance);
    partial void InsertLopHoc(LopHoc instance);
    partial void UpdateLopHoc(LopHoc instance);
    partial void DeleteLopHoc(LopHoc instance);
    partial void InsertNhanVien(NhanVien instance);
    partial void UpdateNhanVien(NhanVien instance);
    partial void DeleteNhanVien(NhanVien instance);
    partial void InsertTaoLopHoc(TaoLopHoc instance);
    partial void UpdateTaoLopHoc(TaoLopHoc instance);
    partial void DeleteTaoLopHoc(TaoLopHoc instance);
    partial void InsertThiThu(ThiThu instance);
    partial void UpdateThiThu(ThiThu instance);
    partial void DeleteThiThu(ThiThu instance);
    #endregion
		
		public QL_TTANHNGUDataContext() : 
				base(global::TTQLAV.Properties.Settings.Default.QL_TTANHNGUConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public QL_TTANHNGUDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QL_TTANHNGUDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QL_TTANHNGUDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QL_TTANHNGUDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<ChiNhanh> ChiNhanhs
		{
			get
			{
				return this.GetTable<ChiNhanh>();
			}
		}
		
		public System.Data.Linq.Table<ChiTiet_CaDay> ChiTiet_CaDays
		{
			get
			{
				return this.GetTable<ChiTiet_CaDay>();
			}
		}
		
		public System.Data.Linq.Table<ChiTietDK_LH> ChiTietDK_LHs
		{
			get
			{
				return this.GetTable<ChiTietDK_LH>();
			}
		}
		
		public System.Data.Linq.Table<ChiTietDK_TT> ChiTietDK_TTs
		{
			get
			{
				return this.GetTable<ChiTietDK_TT>();
			}
		}
		
		public System.Data.Linq.Table<CongViec> CongViecs
		{
			get
			{
				return this.GetTable<CongViec>();
			}
		}
		
		public System.Data.Linq.Table<GiangVien> GiangViens
		{
			get
			{
				return this.GetTable<GiangVien>();
			}
		}
		
		public System.Data.Linq.Table<HoaDon> HoaDons
		{
			get
			{
				return this.GetTable<HoaDon>();
			}
		}
		
		public System.Data.Linq.Table<HocVien> HocViens
		{
			get
			{
				return this.GetTable<HocVien>();
			}
		}
		
		public System.Data.Linq.Table<KetQua> KetQuas
		{
			get
			{
				return this.GetTable<KetQua>();
			}
		}
		
		public System.Data.Linq.Table<LopHoc> LopHocs
		{
			get
			{
				return this.GetTable<LopHoc>();
			}
		}
		
		public System.Data.Linq.Table<NhanVien> NhanViens
		{
			get
			{
				return this.GetTable<NhanVien>();
			}
		}
		
		public System.Data.Linq.Table<TaoLopHoc> TaoLopHocs
		{
			get
			{
				return this.GetTable<TaoLopHoc>();
			}
		}
		
		public System.Data.Linq.Table<ThiThu> ThiThus
		{
			get
			{
				return this.GetTable<ThiThu>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.CapNhatNhanVien")]
		public int CapNhatNhanVien([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NChar(10)")] string manv, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string hotennv, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NChar(13)")] string cccd, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NChar(11)")] string sodt, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Float")] System.Nullable<double> luong, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NChar(10)")] string macn, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NChar(10)")] string maql)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), manv, hotennv, cccd, sodt, luong, macn, maql);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ThemNhanVien")]
		public int ThemNhanVien([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NChar(10)")] string manv, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string hotennv, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NChar(13)")] string cccd, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NChar(11)")] string sodt, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Float")] System.Nullable<double> luong, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NChar(10)")] string macn, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NChar(10)")] string maql)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), manv, hotennv, cccd, sodt, luong, macn, maql);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.XoaNhanVien")]
		public int XoaNhanVien([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NChar(10)")] string manv)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), manv);
			return ((int)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ChiNhanh")]
	public partial class ChiNhanh : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaCN;
		
		private string _TenCN;
		
		private string _DiaChiCN;
		
		private EntitySet<NhanVien> _NhanViens;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaCNChanging(string value);
    partial void OnMaCNChanged();
    partial void OnTenCNChanging(string value);
    partial void OnTenCNChanged();
    partial void OnDiaChiCNChanging(string value);
    partial void OnDiaChiCNChanged();
    #endregion
		
		public ChiNhanh()
		{
			this._NhanViens = new EntitySet<NhanVien>(new Action<NhanVien>(this.attach_NhanViens), new Action<NhanVien>(this.detach_NhanViens));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaCN", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaCN
		{
			get
			{
				return this._MaCN;
			}
			set
			{
				if ((this._MaCN != value))
				{
					this.OnMaCNChanging(value);
					this.SendPropertyChanging();
					this._MaCN = value;
					this.SendPropertyChanged("MaCN");
					this.OnMaCNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenCN", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string TenCN
		{
			get
			{
				return this._TenCN;
			}
			set
			{
				if ((this._TenCN != value))
				{
					this.OnTenCNChanging(value);
					this.SendPropertyChanging();
					this._TenCN = value;
					this.SendPropertyChanged("TenCN");
					this.OnTenCNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaChiCN", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string DiaChiCN
		{
			get
			{
				return this._DiaChiCN;
			}
			set
			{
				if ((this._DiaChiCN != value))
				{
					this.OnDiaChiCNChanging(value);
					this.SendPropertyChanging();
					this._DiaChiCN = value;
					this.SendPropertyChanged("DiaChiCN");
					this.OnDiaChiCNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ChiNhanh_NhanVien", Storage="_NhanViens", ThisKey="MaCN", OtherKey="MaCN")]
		public EntitySet<NhanVien> NhanViens
		{
			get
			{
				return this._NhanViens;
			}
			set
			{
				this._NhanViens.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_NhanViens(NhanVien entity)
		{
			this.SendPropertyChanging();
			entity.ChiNhanh = this;
		}
		
		private void detach_NhanViens(NhanVien entity)
		{
			this.SendPropertyChanging();
			entity.ChiNhanh = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ChiTiet_CaDay")]
	public partial class ChiTiet_CaDay : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaLH;
		
		private string _MaGV;
		
		private System.DateTime _NgayBatDau;
		
		private System.DateTime _NgayKetThuc;
		
		private string _CaDay;
		
		private EntityRef<GiangVien> _GiangVien;
		
		private EntityRef<LopHoc> _LopHoc;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaLHChanging(string value);
    partial void OnMaLHChanged();
    partial void OnMaGVChanging(string value);
    partial void OnMaGVChanged();
    partial void OnNgayBatDauChanging(System.DateTime value);
    partial void OnNgayBatDauChanged();
    partial void OnNgayKetThucChanging(System.DateTime value);
    partial void OnNgayKetThucChanged();
    partial void OnCaDayChanging(string value);
    partial void OnCaDayChanged();
    #endregion
		
		public ChiTiet_CaDay()
		{
			this._GiangVien = default(EntityRef<GiangVien>);
			this._LopHoc = default(EntityRef<LopHoc>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaLH", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaLH
		{
			get
			{
				return this._MaLH;
			}
			set
			{
				if ((this._MaLH != value))
				{
					if (this._LopHoc.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaLHChanging(value);
					this.SendPropertyChanging();
					this._MaLH = value;
					this.SendPropertyChanged("MaLH");
					this.OnMaLHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaGV", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaGV
		{
			get
			{
				return this._MaGV;
			}
			set
			{
				if ((this._MaGV != value))
				{
					if (this._GiangVien.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaGVChanging(value);
					this.SendPropertyChanging();
					this._MaGV = value;
					this.SendPropertyChanged("MaGV");
					this.OnMaGVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayBatDau", DbType="Date NOT NULL")]
		public System.DateTime NgayBatDau
		{
			get
			{
				return this._NgayBatDau;
			}
			set
			{
				if ((this._NgayBatDau != value))
				{
					this.OnNgayBatDauChanging(value);
					this.SendPropertyChanging();
					this._NgayBatDau = value;
					this.SendPropertyChanged("NgayBatDau");
					this.OnNgayBatDauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayKetThuc", DbType="Date NOT NULL")]
		public System.DateTime NgayKetThuc
		{
			get
			{
				return this._NgayKetThuc;
			}
			set
			{
				if ((this._NgayKetThuc != value))
				{
					this.OnNgayKetThucChanging(value);
					this.SendPropertyChanging();
					this._NgayKetThuc = value;
					this.SendPropertyChanged("NgayKetThuc");
					this.OnNgayKetThucChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CaDay", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		public string CaDay
		{
			get
			{
				return this._CaDay;
			}
			set
			{
				if ((this._CaDay != value))
				{
					this.OnCaDayChanging(value);
					this.SendPropertyChanging();
					this._CaDay = value;
					this.SendPropertyChanged("CaDay");
					this.OnCaDayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="GiangVien_ChiTiet_CaDay", Storage="_GiangVien", ThisKey="MaGV", OtherKey="MaGV", IsForeignKey=true)]
		public GiangVien GiangVien
		{
			get
			{
				return this._GiangVien.Entity;
			}
			set
			{
				GiangVien previousValue = this._GiangVien.Entity;
				if (((previousValue != value) 
							|| (this._GiangVien.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._GiangVien.Entity = null;
						previousValue.ChiTiet_CaDays.Remove(this);
					}
					this._GiangVien.Entity = value;
					if ((value != null))
					{
						value.ChiTiet_CaDays.Add(this);
						this._MaGV = value.MaGV;
					}
					else
					{
						this._MaGV = default(string);
					}
					this.SendPropertyChanged("GiangVien");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LopHoc_ChiTiet_CaDay", Storage="_LopHoc", ThisKey="MaLH", OtherKey="MaLH", IsForeignKey=true)]
		public LopHoc LopHoc
		{
			get
			{
				return this._LopHoc.Entity;
			}
			set
			{
				LopHoc previousValue = this._LopHoc.Entity;
				if (((previousValue != value) 
							|| (this._LopHoc.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._LopHoc.Entity = null;
						previousValue.ChiTiet_CaDays.Remove(this);
					}
					this._LopHoc.Entity = value;
					if ((value != null))
					{
						value.ChiTiet_CaDays.Add(this);
						this._MaLH = value.MaLH;
					}
					else
					{
						this._MaLH = default(string);
					}
					this.SendPropertyChanged("LopHoc");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ChiTietDK_LH")]
	public partial class ChiTietDK_LH : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaHV;
		
		private string _MaLH;
		
		private System.DateTime _NgayDK;
		
		private EntityRef<HocVien> _HocVien;
		
		private EntityRef<LopHoc> _LopHoc;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaHVChanging(string value);
    partial void OnMaHVChanged();
    partial void OnMaLHChanging(string value);
    partial void OnMaLHChanged();
    partial void OnNgayDKChanging(System.DateTime value);
    partial void OnNgayDKChanged();
    #endregion
		
		public ChiTietDK_LH()
		{
			this._HocVien = default(EntityRef<HocVien>);
			this._LopHoc = default(EntityRef<LopHoc>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaHV", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaHV
		{
			get
			{
				return this._MaHV;
			}
			set
			{
				if ((this._MaHV != value))
				{
					if (this._HocVien.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaHVChanging(value);
					this.SendPropertyChanging();
					this._MaHV = value;
					this.SendPropertyChanged("MaHV");
					this.OnMaHVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaLH", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaLH
		{
			get
			{
				return this._MaLH;
			}
			set
			{
				if ((this._MaLH != value))
				{
					if (this._LopHoc.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaLHChanging(value);
					this.SendPropertyChanging();
					this._MaLH = value;
					this.SendPropertyChanged("MaLH");
					this.OnMaLHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayDK", DbType="Date NOT NULL")]
		public System.DateTime NgayDK
		{
			get
			{
				return this._NgayDK;
			}
			set
			{
				if ((this._NgayDK != value))
				{
					this.OnNgayDKChanging(value);
					this.SendPropertyChanging();
					this._NgayDK = value;
					this.SendPropertyChanged("NgayDK");
					this.OnNgayDKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HocVien_ChiTietDK_LH", Storage="_HocVien", ThisKey="MaHV", OtherKey="MaHV", IsForeignKey=true)]
		public HocVien HocVien
		{
			get
			{
				return this._HocVien.Entity;
			}
			set
			{
				HocVien previousValue = this._HocVien.Entity;
				if (((previousValue != value) 
							|| (this._HocVien.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._HocVien.Entity = null;
						previousValue.ChiTietDK_LHs.Remove(this);
					}
					this._HocVien.Entity = value;
					if ((value != null))
					{
						value.ChiTietDK_LHs.Add(this);
						this._MaHV = value.MaHV;
					}
					else
					{
						this._MaHV = default(string);
					}
					this.SendPropertyChanged("HocVien");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LopHoc_ChiTietDK_LH", Storage="_LopHoc", ThisKey="MaLH", OtherKey="MaLH", IsForeignKey=true)]
		public LopHoc LopHoc
		{
			get
			{
				return this._LopHoc.Entity;
			}
			set
			{
				LopHoc previousValue = this._LopHoc.Entity;
				if (((previousValue != value) 
							|| (this._LopHoc.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._LopHoc.Entity = null;
						previousValue.ChiTietDK_LHs.Remove(this);
					}
					this._LopHoc.Entity = value;
					if ((value != null))
					{
						value.ChiTietDK_LHs.Add(this);
						this._MaLH = value.MaLH;
					}
					else
					{
						this._MaLH = default(string);
					}
					this.SendPropertyChanged("LopHoc");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ChiTietDK_TT")]
	public partial class ChiTietDK_TT : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaHV;
		
		private string _MaTT;
		
		private System.DateTime _NgayDK;
		
		private EntityRef<HocVien> _HocVien;
		
		private EntityRef<ThiThu> _ThiThu;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaHVChanging(string value);
    partial void OnMaHVChanged();
    partial void OnMaTTChanging(string value);
    partial void OnMaTTChanged();
    partial void OnNgayDKChanging(System.DateTime value);
    partial void OnNgayDKChanged();
    #endregion
		
		public ChiTietDK_TT()
		{
			this._HocVien = default(EntityRef<HocVien>);
			this._ThiThu = default(EntityRef<ThiThu>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaHV", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaHV
		{
			get
			{
				return this._MaHV;
			}
			set
			{
				if ((this._MaHV != value))
				{
					if (this._HocVien.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaHVChanging(value);
					this.SendPropertyChanging();
					this._MaHV = value;
					this.SendPropertyChanged("MaHV");
					this.OnMaHVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaTT", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaTT
		{
			get
			{
				return this._MaTT;
			}
			set
			{
				if ((this._MaTT != value))
				{
					if (this._ThiThu.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaTTChanging(value);
					this.SendPropertyChanging();
					this._MaTT = value;
					this.SendPropertyChanged("MaTT");
					this.OnMaTTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayDK", DbType="Date NOT NULL")]
		public System.DateTime NgayDK
		{
			get
			{
				return this._NgayDK;
			}
			set
			{
				if ((this._NgayDK != value))
				{
					this.OnNgayDKChanging(value);
					this.SendPropertyChanging();
					this._NgayDK = value;
					this.SendPropertyChanged("NgayDK");
					this.OnNgayDKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HocVien_ChiTietDK_TT", Storage="_HocVien", ThisKey="MaHV", OtherKey="MaHV", IsForeignKey=true)]
		public HocVien HocVien
		{
			get
			{
				return this._HocVien.Entity;
			}
			set
			{
				HocVien previousValue = this._HocVien.Entity;
				if (((previousValue != value) 
							|| (this._HocVien.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._HocVien.Entity = null;
						previousValue.ChiTietDK_TTs.Remove(this);
					}
					this._HocVien.Entity = value;
					if ((value != null))
					{
						value.ChiTietDK_TTs.Add(this);
						this._MaHV = value.MaHV;
					}
					else
					{
						this._MaHV = default(string);
					}
					this.SendPropertyChanged("HocVien");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ThiThu_ChiTietDK_TT", Storage="_ThiThu", ThisKey="MaTT", OtherKey="MaTT", IsForeignKey=true)]
		public ThiThu ThiThu
		{
			get
			{
				return this._ThiThu.Entity;
			}
			set
			{
				ThiThu previousValue = this._ThiThu.Entity;
				if (((previousValue != value) 
							|| (this._ThiThu.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._ThiThu.Entity = null;
						previousValue.ChiTietDK_TTs.Remove(this);
					}
					this._ThiThu.Entity = value;
					if ((value != null))
					{
						value.ChiTietDK_TTs.Add(this);
						this._MaTT = value.MaTT;
					}
					else
					{
						this._MaTT = default(string);
					}
					this.SendPropertyChanged("ThiThu");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CongViec")]
	public partial class CongViec : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaCV;
		
		private string _TenCV;
		
		private string _MaNV;
		
		private EntityRef<NhanVien> _NhanVien;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaCVChanging(string value);
    partial void OnMaCVChanged();
    partial void OnTenCVChanging(string value);
    partial void OnTenCVChanged();
    partial void OnMaNVChanging(string value);
    partial void OnMaNVChanged();
    #endregion
		
		public CongViec()
		{
			this._NhanVien = default(EntityRef<NhanVien>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaCV", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaCV
		{
			get
			{
				return this._MaCV;
			}
			set
			{
				if ((this._MaCV != value))
				{
					this.OnMaCVChanging(value);
					this.SendPropertyChanging();
					this._MaCV = value;
					this.SendPropertyChanged("MaCV");
					this.OnMaCVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenCV", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string TenCV
		{
			get
			{
				return this._TenCV;
			}
			set
			{
				if ((this._TenCV != value))
				{
					this.OnTenCVChanging(value);
					this.SendPropertyChanging();
					this._TenCV = value;
					this.SendPropertyChanged("TenCV");
					this.OnTenCVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNV", DbType="NChar(10)")]
		public string MaNV
		{
			get
			{
				return this._MaNV;
			}
			set
			{
				if ((this._MaNV != value))
				{
					if (this._NhanVien.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaNVChanging(value);
					this.SendPropertyChanging();
					this._MaNV = value;
					this.SendPropertyChanged("MaNV");
					this.OnMaNVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhanVien_CongViec", Storage="_NhanVien", ThisKey="MaNV", OtherKey="MaNV", IsForeignKey=true, DeleteRule="SET NULL")]
		public NhanVien NhanVien
		{
			get
			{
				return this._NhanVien.Entity;
			}
			set
			{
				NhanVien previousValue = this._NhanVien.Entity;
				if (((previousValue != value) 
							|| (this._NhanVien.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NhanVien.Entity = null;
						previousValue.CongViecs.Remove(this);
					}
					this._NhanVien.Entity = value;
					if ((value != null))
					{
						value.CongViecs.Add(this);
						this._MaNV = value.MaNV;
					}
					else
					{
						this._MaNV = default(string);
					}
					this.SendPropertyChanged("NhanVien");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.GiangVien")]
	public partial class GiangVien : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaGV;
		
		private string _HoTen;
		
		private string _CCCD;
		
		private string _SoDT;
		
		private System.Nullable<double> _Luong;
		
		private EntitySet<ChiTiet_CaDay> _ChiTiet_CaDays;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaGVChanging(string value);
    partial void OnMaGVChanged();
    partial void OnHoTenChanging(string value);
    partial void OnHoTenChanged();
    partial void OnCCCDChanging(string value);
    partial void OnCCCDChanged();
    partial void OnSoDTChanging(string value);
    partial void OnSoDTChanged();
    partial void OnLuongChanging(System.Nullable<double> value);
    partial void OnLuongChanged();
    #endregion
		
		public GiangVien()
		{
			this._ChiTiet_CaDays = new EntitySet<ChiTiet_CaDay>(new Action<ChiTiet_CaDay>(this.attach_ChiTiet_CaDays), new Action<ChiTiet_CaDay>(this.detach_ChiTiet_CaDays));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaGV", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaGV
		{
			get
			{
				return this._MaGV;
			}
			set
			{
				if ((this._MaGV != value))
				{
					this.OnMaGVChanging(value);
					this.SendPropertyChanging();
					this._MaGV = value;
					this.SendPropertyChanged("MaGV");
					this.OnMaGVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoTen", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string HoTen
		{
			get
			{
				return this._HoTen;
			}
			set
			{
				if ((this._HoTen != value))
				{
					this.OnHoTenChanging(value);
					this.SendPropertyChanging();
					this._HoTen = value;
					this.SendPropertyChanged("HoTen");
					this.OnHoTenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CCCD", DbType="NChar(13) NOT NULL", CanBeNull=false)]
		public string CCCD
		{
			get
			{
				return this._CCCD;
			}
			set
			{
				if ((this._CCCD != value))
				{
					this.OnCCCDChanging(value);
					this.SendPropertyChanging();
					this._CCCD = value;
					this.SendPropertyChanged("CCCD");
					this.OnCCCDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoDT", DbType="NChar(11) NOT NULL", CanBeNull=false)]
		public string SoDT
		{
			get
			{
				return this._SoDT;
			}
			set
			{
				if ((this._SoDT != value))
				{
					this.OnSoDTChanging(value);
					this.SendPropertyChanging();
					this._SoDT = value;
					this.SendPropertyChanged("SoDT");
					this.OnSoDTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Luong", DbType="Float")]
		public System.Nullable<double> Luong
		{
			get
			{
				return this._Luong;
			}
			set
			{
				if ((this._Luong != value))
				{
					this.OnLuongChanging(value);
					this.SendPropertyChanging();
					this._Luong = value;
					this.SendPropertyChanged("Luong");
					this.OnLuongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="GiangVien_ChiTiet_CaDay", Storage="_ChiTiet_CaDays", ThisKey="MaGV", OtherKey="MaGV")]
		public EntitySet<ChiTiet_CaDay> ChiTiet_CaDays
		{
			get
			{
				return this._ChiTiet_CaDays;
			}
			set
			{
				this._ChiTiet_CaDays.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ChiTiet_CaDays(ChiTiet_CaDay entity)
		{
			this.SendPropertyChanging();
			entity.GiangVien = this;
		}
		
		private void detach_ChiTiet_CaDays(ChiTiet_CaDay entity)
		{
			this.SendPropertyChanging();
			entity.GiangVien = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.HoaDon")]
	public partial class HoaDon : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaHD;
		
		private System.DateTime _NgayGD;
		
		private double _SoTien;
		
		private string _MaHV;
		
		private EntityRef<HocVien> _HocVien;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaHDChanging(string value);
    partial void OnMaHDChanged();
    partial void OnNgayGDChanging(System.DateTime value);
    partial void OnNgayGDChanged();
    partial void OnSoTienChanging(double value);
    partial void OnSoTienChanged();
    partial void OnMaHVChanging(string value);
    partial void OnMaHVChanged();
    #endregion
		
		public HoaDon()
		{
			this._HocVien = default(EntityRef<HocVien>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaHD", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaHD
		{
			get
			{
				return this._MaHD;
			}
			set
			{
				if ((this._MaHD != value))
				{
					this.OnMaHDChanging(value);
					this.SendPropertyChanging();
					this._MaHD = value;
					this.SendPropertyChanged("MaHD");
					this.OnMaHDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayGD", DbType="Date NOT NULL")]
		public System.DateTime NgayGD
		{
			get
			{
				return this._NgayGD;
			}
			set
			{
				if ((this._NgayGD != value))
				{
					this.OnNgayGDChanging(value);
					this.SendPropertyChanging();
					this._NgayGD = value;
					this.SendPropertyChanged("NgayGD");
					this.OnNgayGDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoTien", DbType="Float NOT NULL")]
		public double SoTien
		{
			get
			{
				return this._SoTien;
			}
			set
			{
				if ((this._SoTien != value))
				{
					this.OnSoTienChanging(value);
					this.SendPropertyChanging();
					this._SoTien = value;
					this.SendPropertyChanged("SoTien");
					this.OnSoTienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaHV", DbType="NChar(10)")]
		public string MaHV
		{
			get
			{
				return this._MaHV;
			}
			set
			{
				if ((this._MaHV != value))
				{
					if (this._HocVien.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaHVChanging(value);
					this.SendPropertyChanging();
					this._MaHV = value;
					this.SendPropertyChanged("MaHV");
					this.OnMaHVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HocVien_HoaDon", Storage="_HocVien", ThisKey="MaHV", OtherKey="MaHV", IsForeignKey=true, DeleteRule="SET NULL")]
		public HocVien HocVien
		{
			get
			{
				return this._HocVien.Entity;
			}
			set
			{
				HocVien previousValue = this._HocVien.Entity;
				if (((previousValue != value) 
							|| (this._HocVien.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._HocVien.Entity = null;
						previousValue.HoaDons.Remove(this);
					}
					this._HocVien.Entity = value;
					if ((value != null))
					{
						value.HoaDons.Add(this);
						this._MaHV = value.MaHV;
					}
					else
					{
						this._MaHV = default(string);
					}
					this.SendPropertyChanged("HocVien");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.HocVien")]
	public partial class HocVien : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaHV;
		
		private string _HoTenHV;
		
		private System.DateTime _NgaySinh;
		
		private string _GioiTinh;
		
		private string _SoDT;
		
		private string _DiaChiHV;
		
		private EntitySet<ChiTietDK_LH> _ChiTietDK_LHs;
		
		private EntitySet<ChiTietDK_TT> _ChiTietDK_TTs;
		
		private EntitySet<HoaDon> _HoaDons;
		
		private EntitySet<KetQua> _KetQuas;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaHVChanging(string value);
    partial void OnMaHVChanged();
    partial void OnHoTenHVChanging(string value);
    partial void OnHoTenHVChanged();
    partial void OnNgaySinhChanging(System.DateTime value);
    partial void OnNgaySinhChanged();
    partial void OnGioiTinhChanging(string value);
    partial void OnGioiTinhChanged();
    partial void OnSoDTChanging(string value);
    partial void OnSoDTChanged();
    partial void OnDiaChiHVChanging(string value);
    partial void OnDiaChiHVChanged();
    #endregion
		
		public HocVien()
		{
			this._ChiTietDK_LHs = new EntitySet<ChiTietDK_LH>(new Action<ChiTietDK_LH>(this.attach_ChiTietDK_LHs), new Action<ChiTietDK_LH>(this.detach_ChiTietDK_LHs));
			this._ChiTietDK_TTs = new EntitySet<ChiTietDK_TT>(new Action<ChiTietDK_TT>(this.attach_ChiTietDK_TTs), new Action<ChiTietDK_TT>(this.detach_ChiTietDK_TTs));
			this._HoaDons = new EntitySet<HoaDon>(new Action<HoaDon>(this.attach_HoaDons), new Action<HoaDon>(this.detach_HoaDons));
			this._KetQuas = new EntitySet<KetQua>(new Action<KetQua>(this.attach_KetQuas), new Action<KetQua>(this.detach_KetQuas));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaHV", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaHV
		{
			get
			{
				return this._MaHV;
			}
			set
			{
				if ((this._MaHV != value))
				{
					this.OnMaHVChanging(value);
					this.SendPropertyChanging();
					this._MaHV = value;
					this.SendPropertyChanged("MaHV");
					this.OnMaHVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoTenHV", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string HoTenHV
		{
			get
			{
				return this._HoTenHV;
			}
			set
			{
				if ((this._HoTenHV != value))
				{
					this.OnHoTenHVChanging(value);
					this.SendPropertyChanging();
					this._HoTenHV = value;
					this.SendPropertyChanged("HoTenHV");
					this.OnHoTenHVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgaySinh", DbType="Date NOT NULL")]
		public System.DateTime NgaySinh
		{
			get
			{
				return this._NgaySinh;
			}
			set
			{
				if ((this._NgaySinh != value))
				{
					this.OnNgaySinhChanging(value);
					this.SendPropertyChanging();
					this._NgaySinh = value;
					this.SendPropertyChanged("NgaySinh");
					this.OnNgaySinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GioiTinh", DbType="NVarChar(3)")]
		public string GioiTinh
		{
			get
			{
				return this._GioiTinh;
			}
			set
			{
				if ((this._GioiTinh != value))
				{
					this.OnGioiTinhChanging(value);
					this.SendPropertyChanging();
					this._GioiTinh = value;
					this.SendPropertyChanged("GioiTinh");
					this.OnGioiTinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoDT", DbType="NChar(11)")]
		public string SoDT
		{
			get
			{
				return this._SoDT;
			}
			set
			{
				if ((this._SoDT != value))
				{
					this.OnSoDTChanging(value);
					this.SendPropertyChanging();
					this._SoDT = value;
					this.SendPropertyChanged("SoDT");
					this.OnSoDTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaChiHV", DbType="NVarChar(100)")]
		public string DiaChiHV
		{
			get
			{
				return this._DiaChiHV;
			}
			set
			{
				if ((this._DiaChiHV != value))
				{
					this.OnDiaChiHVChanging(value);
					this.SendPropertyChanging();
					this._DiaChiHV = value;
					this.SendPropertyChanged("DiaChiHV");
					this.OnDiaChiHVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HocVien_ChiTietDK_LH", Storage="_ChiTietDK_LHs", ThisKey="MaHV", OtherKey="MaHV")]
		public EntitySet<ChiTietDK_LH> ChiTietDK_LHs
		{
			get
			{
				return this._ChiTietDK_LHs;
			}
			set
			{
				this._ChiTietDK_LHs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HocVien_ChiTietDK_TT", Storage="_ChiTietDK_TTs", ThisKey="MaHV", OtherKey="MaHV")]
		public EntitySet<ChiTietDK_TT> ChiTietDK_TTs
		{
			get
			{
				return this._ChiTietDK_TTs;
			}
			set
			{
				this._ChiTietDK_TTs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HocVien_HoaDon", Storage="_HoaDons", ThisKey="MaHV", OtherKey="MaHV")]
		public EntitySet<HoaDon> HoaDons
		{
			get
			{
				return this._HoaDons;
			}
			set
			{
				this._HoaDons.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HocVien_KetQua", Storage="_KetQuas", ThisKey="MaHV", OtherKey="MaHV")]
		public EntitySet<KetQua> KetQuas
		{
			get
			{
				return this._KetQuas;
			}
			set
			{
				this._KetQuas.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ChiTietDK_LHs(ChiTietDK_LH entity)
		{
			this.SendPropertyChanging();
			entity.HocVien = this;
		}
		
		private void detach_ChiTietDK_LHs(ChiTietDK_LH entity)
		{
			this.SendPropertyChanging();
			entity.HocVien = null;
		}
		
		private void attach_ChiTietDK_TTs(ChiTietDK_TT entity)
		{
			this.SendPropertyChanging();
			entity.HocVien = this;
		}
		
		private void detach_ChiTietDK_TTs(ChiTietDK_TT entity)
		{
			this.SendPropertyChanging();
			entity.HocVien = null;
		}
		
		private void attach_HoaDons(HoaDon entity)
		{
			this.SendPropertyChanging();
			entity.HocVien = this;
		}
		
		private void detach_HoaDons(HoaDon entity)
		{
			this.SendPropertyChanging();
			entity.HocVien = null;
		}
		
		private void attach_KetQuas(KetQua entity)
		{
			this.SendPropertyChanging();
			entity.HocVien = this;
		}
		
		private void detach_KetQuas(KetQua entity)
		{
			this.SendPropertyChanging();
			entity.HocVien = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.KetQua")]
	public partial class KetQua : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaHV;
		
		private string _MaTT;
		
		private System.Nullable<int> _SoCauDocDung;
		
		private System.Nullable<int> _SoCauNgheDung;
		
		private System.Nullable<int> _Diem;
		
		private EntityRef<HocVien> _HocVien;
		
		private EntityRef<ThiThu> _ThiThu;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaHVChanging(string value);
    partial void OnMaHVChanged();
    partial void OnMaTTChanging(string value);
    partial void OnMaTTChanged();
    partial void OnSoCauDocDungChanging(System.Nullable<int> value);
    partial void OnSoCauDocDungChanged();
    partial void OnSoCauNgheDungChanging(System.Nullable<int> value);
    partial void OnSoCauNgheDungChanged();
    partial void OnDiemChanging(System.Nullable<int> value);
    partial void OnDiemChanged();
    #endregion
		
		public KetQua()
		{
			this._HocVien = default(EntityRef<HocVien>);
			this._ThiThu = default(EntityRef<ThiThu>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaHV", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaHV
		{
			get
			{
				return this._MaHV;
			}
			set
			{
				if ((this._MaHV != value))
				{
					if (this._HocVien.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaHVChanging(value);
					this.SendPropertyChanging();
					this._MaHV = value;
					this.SendPropertyChanged("MaHV");
					this.OnMaHVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaTT", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaTT
		{
			get
			{
				return this._MaTT;
			}
			set
			{
				if ((this._MaTT != value))
				{
					if (this._ThiThu.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaTTChanging(value);
					this.SendPropertyChanging();
					this._MaTT = value;
					this.SendPropertyChanged("MaTT");
					this.OnMaTTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoCauDocDung", DbType="Int")]
		public System.Nullable<int> SoCauDocDung
		{
			get
			{
				return this._SoCauDocDung;
			}
			set
			{
				if ((this._SoCauDocDung != value))
				{
					this.OnSoCauDocDungChanging(value);
					this.SendPropertyChanging();
					this._SoCauDocDung = value;
					this.SendPropertyChanged("SoCauDocDung");
					this.OnSoCauDocDungChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoCauNgheDung", DbType="Int")]
		public System.Nullable<int> SoCauNgheDung
		{
			get
			{
				return this._SoCauNgheDung;
			}
			set
			{
				if ((this._SoCauNgheDung != value))
				{
					this.OnSoCauNgheDungChanging(value);
					this.SendPropertyChanging();
					this._SoCauNgheDung = value;
					this.SendPropertyChanged("SoCauNgheDung");
					this.OnSoCauNgheDungChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Diem", DbType="Int")]
		public System.Nullable<int> Diem
		{
			get
			{
				return this._Diem;
			}
			set
			{
				if ((this._Diem != value))
				{
					this.OnDiemChanging(value);
					this.SendPropertyChanging();
					this._Diem = value;
					this.SendPropertyChanged("Diem");
					this.OnDiemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HocVien_KetQua", Storage="_HocVien", ThisKey="MaHV", OtherKey="MaHV", IsForeignKey=true)]
		public HocVien HocVien
		{
			get
			{
				return this._HocVien.Entity;
			}
			set
			{
				HocVien previousValue = this._HocVien.Entity;
				if (((previousValue != value) 
							|| (this._HocVien.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._HocVien.Entity = null;
						previousValue.KetQuas.Remove(this);
					}
					this._HocVien.Entity = value;
					if ((value != null))
					{
						value.KetQuas.Add(this);
						this._MaHV = value.MaHV;
					}
					else
					{
						this._MaHV = default(string);
					}
					this.SendPropertyChanged("HocVien");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ThiThu_KetQua", Storage="_ThiThu", ThisKey="MaTT", OtherKey="MaTT", IsForeignKey=true)]
		public ThiThu ThiThu
		{
			get
			{
				return this._ThiThu.Entity;
			}
			set
			{
				ThiThu previousValue = this._ThiThu.Entity;
				if (((previousValue != value) 
							|| (this._ThiThu.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._ThiThu.Entity = null;
						previousValue.KetQuas.Remove(this);
					}
					this._ThiThu.Entity = value;
					if ((value != null))
					{
						value.KetQuas.Add(this);
						this._MaTT = value.MaTT;
					}
					else
					{
						this._MaTT = default(string);
					}
					this.SendPropertyChanged("ThiThu");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LopHoc")]
	public partial class LopHoc : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaLH;
		
		private string _TenLH;
		
		private string _TenPhongHoc;
		
		private double _HocPhi;
		
		private int _SoBuoiHoc;
		
		private int _SoLuongHV;
		
		private string _TrangThai;
		
		private EntitySet<ChiTiet_CaDay> _ChiTiet_CaDays;
		
		private EntitySet<ChiTietDK_LH> _ChiTietDK_LHs;
		
		private EntitySet<TaoLopHoc> _TaoLopHocs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaLHChanging(string value);
    partial void OnMaLHChanged();
    partial void OnTenLHChanging(string value);
    partial void OnTenLHChanged();
    partial void OnTenPhongHocChanging(string value);
    partial void OnTenPhongHocChanged();
    partial void OnHocPhiChanging(double value);
    partial void OnHocPhiChanged();
    partial void OnSoBuoiHocChanging(int value);
    partial void OnSoBuoiHocChanged();
    partial void OnSoLuongHVChanging(int value);
    partial void OnSoLuongHVChanged();
    partial void OnTrangThaiChanging(string value);
    partial void OnTrangThaiChanged();
    #endregion
		
		public LopHoc()
		{
			this._ChiTiet_CaDays = new EntitySet<ChiTiet_CaDay>(new Action<ChiTiet_CaDay>(this.attach_ChiTiet_CaDays), new Action<ChiTiet_CaDay>(this.detach_ChiTiet_CaDays));
			this._ChiTietDK_LHs = new EntitySet<ChiTietDK_LH>(new Action<ChiTietDK_LH>(this.attach_ChiTietDK_LHs), new Action<ChiTietDK_LH>(this.detach_ChiTietDK_LHs));
			this._TaoLopHocs = new EntitySet<TaoLopHoc>(new Action<TaoLopHoc>(this.attach_TaoLopHocs), new Action<TaoLopHoc>(this.detach_TaoLopHocs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaLH", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaLH
		{
			get
			{
				return this._MaLH;
			}
			set
			{
				if ((this._MaLH != value))
				{
					this.OnMaLHChanging(value);
					this.SendPropertyChanging();
					this._MaLH = value;
					this.SendPropertyChanged("MaLH");
					this.OnMaLHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenLH", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string TenLH
		{
			get
			{
				return this._TenLH;
			}
			set
			{
				if ((this._TenLH != value))
				{
					this.OnTenLHChanging(value);
					this.SendPropertyChanging();
					this._TenLH = value;
					this.SendPropertyChanged("TenLH");
					this.OnTenLHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenPhongHoc", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string TenPhongHoc
		{
			get
			{
				return this._TenPhongHoc;
			}
			set
			{
				if ((this._TenPhongHoc != value))
				{
					this.OnTenPhongHocChanging(value);
					this.SendPropertyChanging();
					this._TenPhongHoc = value;
					this.SendPropertyChanged("TenPhongHoc");
					this.OnTenPhongHocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HocPhi", DbType="Float NOT NULL")]
		public double HocPhi
		{
			get
			{
				return this._HocPhi;
			}
			set
			{
				if ((this._HocPhi != value))
				{
					this.OnHocPhiChanging(value);
					this.SendPropertyChanging();
					this._HocPhi = value;
					this.SendPropertyChanged("HocPhi");
					this.OnHocPhiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoBuoiHoc", DbType="Int NOT NULL")]
		public int SoBuoiHoc
		{
			get
			{
				return this._SoBuoiHoc;
			}
			set
			{
				if ((this._SoBuoiHoc != value))
				{
					this.OnSoBuoiHocChanging(value);
					this.SendPropertyChanging();
					this._SoBuoiHoc = value;
					this.SendPropertyChanged("SoBuoiHoc");
					this.OnSoBuoiHocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoLuongHV", DbType="Int NOT NULL")]
		public int SoLuongHV
		{
			get
			{
				return this._SoLuongHV;
			}
			set
			{
				if ((this._SoLuongHV != value))
				{
					this.OnSoLuongHVChanging(value);
					this.SendPropertyChanging();
					this._SoLuongHV = value;
					this.SendPropertyChanged("SoLuongHV");
					this.OnSoLuongHVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TrangThai", DbType="NChar(10)")]
		public string TrangThai
		{
			get
			{
				return this._TrangThai;
			}
			set
			{
				if ((this._TrangThai != value))
				{
					this.OnTrangThaiChanging(value);
					this.SendPropertyChanging();
					this._TrangThai = value;
					this.SendPropertyChanged("TrangThai");
					this.OnTrangThaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LopHoc_ChiTiet_CaDay", Storage="_ChiTiet_CaDays", ThisKey="MaLH", OtherKey="MaLH")]
		public EntitySet<ChiTiet_CaDay> ChiTiet_CaDays
		{
			get
			{
				return this._ChiTiet_CaDays;
			}
			set
			{
				this._ChiTiet_CaDays.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LopHoc_ChiTietDK_LH", Storage="_ChiTietDK_LHs", ThisKey="MaLH", OtherKey="MaLH")]
		public EntitySet<ChiTietDK_LH> ChiTietDK_LHs
		{
			get
			{
				return this._ChiTietDK_LHs;
			}
			set
			{
				this._ChiTietDK_LHs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LopHoc_TaoLopHoc", Storage="_TaoLopHocs", ThisKey="MaLH", OtherKey="MaLH")]
		public EntitySet<TaoLopHoc> TaoLopHocs
		{
			get
			{
				return this._TaoLopHocs;
			}
			set
			{
				this._TaoLopHocs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ChiTiet_CaDays(ChiTiet_CaDay entity)
		{
			this.SendPropertyChanging();
			entity.LopHoc = this;
		}
		
		private void detach_ChiTiet_CaDays(ChiTiet_CaDay entity)
		{
			this.SendPropertyChanging();
			entity.LopHoc = null;
		}
		
		private void attach_ChiTietDK_LHs(ChiTietDK_LH entity)
		{
			this.SendPropertyChanging();
			entity.LopHoc = this;
		}
		
		private void detach_ChiTietDK_LHs(ChiTietDK_LH entity)
		{
			this.SendPropertyChanging();
			entity.LopHoc = null;
		}
		
		private void attach_TaoLopHocs(TaoLopHoc entity)
		{
			this.SendPropertyChanging();
			entity.LopHoc = this;
		}
		
		private void detach_TaoLopHocs(TaoLopHoc entity)
		{
			this.SendPropertyChanging();
			entity.LopHoc = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NhanVien")]
	public partial class NhanVien : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaNV;
		
		private string _HoTenNV;
		
		private string _CCCD;
		
		private string _SoDT;
		
		private System.Nullable<double> _Luong;
		
		private string _MaCN;
		
		private string _MaQL;
		
		private EntitySet<CongViec> _CongViecs;
		
		private EntitySet<NhanVien> _NhanViens;
		
		private EntitySet<TaoLopHoc> _TaoLopHocs;
		
		private EntitySet<ThiThu> _ThiThus;
		
		private EntityRef<ChiNhanh> _ChiNhanh;
		
		private EntityRef<NhanVien> _NhanVien1;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaNVChanging(string value);
    partial void OnMaNVChanged();
    partial void OnHoTenNVChanging(string value);
    partial void OnHoTenNVChanged();
    partial void OnCCCDChanging(string value);
    partial void OnCCCDChanged();
    partial void OnSoDTChanging(string value);
    partial void OnSoDTChanged();
    partial void OnLuongChanging(System.Nullable<double> value);
    partial void OnLuongChanged();
    partial void OnMaCNChanging(string value);
    partial void OnMaCNChanged();
    partial void OnMaQLChanging(string value);
    partial void OnMaQLChanged();
    #endregion
		
		public NhanVien()
		{
			this._CongViecs = new EntitySet<CongViec>(new Action<CongViec>(this.attach_CongViecs), new Action<CongViec>(this.detach_CongViecs));
			this._NhanViens = new EntitySet<NhanVien>(new Action<NhanVien>(this.attach_NhanViens), new Action<NhanVien>(this.detach_NhanViens));
			this._TaoLopHocs = new EntitySet<TaoLopHoc>(new Action<TaoLopHoc>(this.attach_TaoLopHocs), new Action<TaoLopHoc>(this.detach_TaoLopHocs));
			this._ThiThus = new EntitySet<ThiThu>(new Action<ThiThu>(this.attach_ThiThus), new Action<ThiThu>(this.detach_ThiThus));
			this._ChiNhanh = default(EntityRef<ChiNhanh>);
			this._NhanVien1 = default(EntityRef<NhanVien>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNV", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaNV
		{
			get
			{
				return this._MaNV;
			}
			set
			{
				if ((this._MaNV != value))
				{
					this.OnMaNVChanging(value);
					this.SendPropertyChanging();
					this._MaNV = value;
					this.SendPropertyChanged("MaNV");
					this.OnMaNVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoTenNV", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string HoTenNV
		{
			get
			{
				return this._HoTenNV;
			}
			set
			{
				if ((this._HoTenNV != value))
				{
					this.OnHoTenNVChanging(value);
					this.SendPropertyChanging();
					this._HoTenNV = value;
					this.SendPropertyChanged("HoTenNV");
					this.OnHoTenNVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CCCD", DbType="NChar(13) NOT NULL", CanBeNull=false)]
		public string CCCD
		{
			get
			{
				return this._CCCD;
			}
			set
			{
				if ((this._CCCD != value))
				{
					this.OnCCCDChanging(value);
					this.SendPropertyChanging();
					this._CCCD = value;
					this.SendPropertyChanged("CCCD");
					this.OnCCCDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoDT", DbType="NChar(11) NOT NULL", CanBeNull=false)]
		public string SoDT
		{
			get
			{
				return this._SoDT;
			}
			set
			{
				if ((this._SoDT != value))
				{
					this.OnSoDTChanging(value);
					this.SendPropertyChanging();
					this._SoDT = value;
					this.SendPropertyChanged("SoDT");
					this.OnSoDTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Luong", DbType="Float")]
		public System.Nullable<double> Luong
		{
			get
			{
				return this._Luong;
			}
			set
			{
				if ((this._Luong != value))
				{
					this.OnLuongChanging(value);
					this.SendPropertyChanging();
					this._Luong = value;
					this.SendPropertyChanged("Luong");
					this.OnLuongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaCN", DbType="NChar(10)")]
		public string MaCN
		{
			get
			{
				return this._MaCN;
			}
			set
			{
				if ((this._MaCN != value))
				{
					if (this._ChiNhanh.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaCNChanging(value);
					this.SendPropertyChanging();
					this._MaCN = value;
					this.SendPropertyChanged("MaCN");
					this.OnMaCNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaQL", DbType="NChar(10)")]
		public string MaQL
		{
			get
			{
				return this._MaQL;
			}
			set
			{
				if ((this._MaQL != value))
				{
					if (this._NhanVien1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaQLChanging(value);
					this.SendPropertyChanging();
					this._MaQL = value;
					this.SendPropertyChanged("MaQL");
					this.OnMaQLChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhanVien_CongViec", Storage="_CongViecs", ThisKey="MaNV", OtherKey="MaNV")]
		public EntitySet<CongViec> CongViecs
		{
			get
			{
				return this._CongViecs;
			}
			set
			{
				this._CongViecs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhanVien_NhanVien", Storage="_NhanViens", ThisKey="MaNV", OtherKey="MaQL")]
		public EntitySet<NhanVien> NhanViens
		{
			get
			{
				return this._NhanViens;
			}
			set
			{
				this._NhanViens.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhanVien_TaoLopHoc", Storage="_TaoLopHocs", ThisKey="MaNV", OtherKey="MaQL")]
		public EntitySet<TaoLopHoc> TaoLopHocs
		{
			get
			{
				return this._TaoLopHocs;
			}
			set
			{
				this._TaoLopHocs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhanVien_ThiThu", Storage="_ThiThus", ThisKey="MaNV", OtherKey="MaNV")]
		public EntitySet<ThiThu> ThiThus
		{
			get
			{
				return this._ThiThus;
			}
			set
			{
				this._ThiThus.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ChiNhanh_NhanVien", Storage="_ChiNhanh", ThisKey="MaCN", OtherKey="MaCN", IsForeignKey=true, DeleteRule="SET NULL")]
		public ChiNhanh ChiNhanh
		{
			get
			{
				return this._ChiNhanh.Entity;
			}
			set
			{
				ChiNhanh previousValue = this._ChiNhanh.Entity;
				if (((previousValue != value) 
							|| (this._ChiNhanh.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._ChiNhanh.Entity = null;
						previousValue.NhanViens.Remove(this);
					}
					this._ChiNhanh.Entity = value;
					if ((value != null))
					{
						value.NhanViens.Add(this);
						this._MaCN = value.MaCN;
					}
					else
					{
						this._MaCN = default(string);
					}
					this.SendPropertyChanged("ChiNhanh");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhanVien_NhanVien", Storage="_NhanVien1", ThisKey="MaQL", OtherKey="MaNV", IsForeignKey=true)]
		public NhanVien NhanVien1
		{
			get
			{
				return this._NhanVien1.Entity;
			}
			set
			{
				NhanVien previousValue = this._NhanVien1.Entity;
				if (((previousValue != value) 
							|| (this._NhanVien1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NhanVien1.Entity = null;
						previousValue.NhanViens.Remove(this);
					}
					this._NhanVien1.Entity = value;
					if ((value != null))
					{
						value.NhanViens.Add(this);
						this._MaQL = value.MaNV;
					}
					else
					{
						this._MaQL = default(string);
					}
					this.SendPropertyChanged("NhanVien1");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CongViecs(CongViec entity)
		{
			this.SendPropertyChanging();
			entity.NhanVien = this;
		}
		
		private void detach_CongViecs(CongViec entity)
		{
			this.SendPropertyChanging();
			entity.NhanVien = null;
		}
		
		private void attach_NhanViens(NhanVien entity)
		{
			this.SendPropertyChanging();
			entity.NhanVien1 = this;
		}
		
		private void detach_NhanViens(NhanVien entity)
		{
			this.SendPropertyChanging();
			entity.NhanVien1 = null;
		}
		
		private void attach_TaoLopHocs(TaoLopHoc entity)
		{
			this.SendPropertyChanging();
			entity.NhanVien = this;
		}
		
		private void detach_TaoLopHocs(TaoLopHoc entity)
		{
			this.SendPropertyChanging();
			entity.NhanVien = null;
		}
		
		private void attach_ThiThus(ThiThu entity)
		{
			this.SendPropertyChanging();
			entity.NhanVien = this;
		}
		
		private void detach_ThiThus(ThiThu entity)
		{
			this.SendPropertyChanging();
			entity.NhanVien = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TaoLopHoc")]
	public partial class TaoLopHoc : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaQL;
		
		private string _MaLH;
		
		private System.Nullable<System.DateTime> _NgayTaoLH;
		
		private EntityRef<LopHoc> _LopHoc;
		
		private EntityRef<NhanVien> _NhanVien;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaQLChanging(string value);
    partial void OnMaQLChanged();
    partial void OnMaLHChanging(string value);
    partial void OnMaLHChanged();
    partial void OnNgayTaoLHChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayTaoLHChanged();
    #endregion
		
		public TaoLopHoc()
		{
			this._LopHoc = default(EntityRef<LopHoc>);
			this._NhanVien = default(EntityRef<NhanVien>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaQL", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaQL
		{
			get
			{
				return this._MaQL;
			}
			set
			{
				if ((this._MaQL != value))
				{
					if (this._NhanVien.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaQLChanging(value);
					this.SendPropertyChanging();
					this._MaQL = value;
					this.SendPropertyChanged("MaQL");
					this.OnMaQLChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaLH", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaLH
		{
			get
			{
				return this._MaLH;
			}
			set
			{
				if ((this._MaLH != value))
				{
					if (this._LopHoc.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaLHChanging(value);
					this.SendPropertyChanging();
					this._MaLH = value;
					this.SendPropertyChanged("MaLH");
					this.OnMaLHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayTaoLH", DbType="Date")]
		public System.Nullable<System.DateTime> NgayTaoLH
		{
			get
			{
				return this._NgayTaoLH;
			}
			set
			{
				if ((this._NgayTaoLH != value))
				{
					this.OnNgayTaoLHChanging(value);
					this.SendPropertyChanging();
					this._NgayTaoLH = value;
					this.SendPropertyChanged("NgayTaoLH");
					this.OnNgayTaoLHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LopHoc_TaoLopHoc", Storage="_LopHoc", ThisKey="MaLH", OtherKey="MaLH", IsForeignKey=true)]
		public LopHoc LopHoc
		{
			get
			{
				return this._LopHoc.Entity;
			}
			set
			{
				LopHoc previousValue = this._LopHoc.Entity;
				if (((previousValue != value) 
							|| (this._LopHoc.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._LopHoc.Entity = null;
						previousValue.TaoLopHocs.Remove(this);
					}
					this._LopHoc.Entity = value;
					if ((value != null))
					{
						value.TaoLopHocs.Add(this);
						this._MaLH = value.MaLH;
					}
					else
					{
						this._MaLH = default(string);
					}
					this.SendPropertyChanged("LopHoc");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhanVien_TaoLopHoc", Storage="_NhanVien", ThisKey="MaQL", OtherKey="MaNV", IsForeignKey=true)]
		public NhanVien NhanVien
		{
			get
			{
				return this._NhanVien.Entity;
			}
			set
			{
				NhanVien previousValue = this._NhanVien.Entity;
				if (((previousValue != value) 
							|| (this._NhanVien.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NhanVien.Entity = null;
						previousValue.TaoLopHocs.Remove(this);
					}
					this._NhanVien.Entity = value;
					if ((value != null))
					{
						value.TaoLopHocs.Add(this);
						this._MaQL = value.MaNV;
					}
					else
					{
						this._MaQL = default(string);
					}
					this.SendPropertyChanged("NhanVien");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ThiThu")]
	public partial class ThiThu : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaTT;
		
		private string _PhongThi;
		
		private System.DateTime _NgayThi;
		
		private System.TimeSpan _GioThi;
		
		private int _GioiHan;
		
		private string _MaNV;
		
		private EntitySet<ChiTietDK_TT> _ChiTietDK_TTs;
		
		private EntitySet<KetQua> _KetQuas;
		
		private EntityRef<NhanVien> _NhanVien;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaTTChanging(string value);
    partial void OnMaTTChanged();
    partial void OnPhongThiChanging(string value);
    partial void OnPhongThiChanged();
    partial void OnNgayThiChanging(System.DateTime value);
    partial void OnNgayThiChanged();
    partial void OnGioThiChanging(System.TimeSpan value);
    partial void OnGioThiChanged();
    partial void OnGioiHanChanging(int value);
    partial void OnGioiHanChanged();
    partial void OnMaNVChanging(string value);
    partial void OnMaNVChanged();
    #endregion
		
		public ThiThu()
		{
			this._ChiTietDK_TTs = new EntitySet<ChiTietDK_TT>(new Action<ChiTietDK_TT>(this.attach_ChiTietDK_TTs), new Action<ChiTietDK_TT>(this.detach_ChiTietDK_TTs));
			this._KetQuas = new EntitySet<KetQua>(new Action<KetQua>(this.attach_KetQuas), new Action<KetQua>(this.detach_KetQuas));
			this._NhanVien = default(EntityRef<NhanVien>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaTT", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaTT
		{
			get
			{
				return this._MaTT;
			}
			set
			{
				if ((this._MaTT != value))
				{
					this.OnMaTTChanging(value);
					this.SendPropertyChanging();
					this._MaTT = value;
					this.SendPropertyChanged("MaTT");
					this.OnMaTTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PhongThi", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		public string PhongThi
		{
			get
			{
				return this._PhongThi;
			}
			set
			{
				if ((this._PhongThi != value))
				{
					this.OnPhongThiChanging(value);
					this.SendPropertyChanging();
					this._PhongThi = value;
					this.SendPropertyChanged("PhongThi");
					this.OnPhongThiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayThi", DbType="Date NOT NULL")]
		public System.DateTime NgayThi
		{
			get
			{
				return this._NgayThi;
			}
			set
			{
				if ((this._NgayThi != value))
				{
					this.OnNgayThiChanging(value);
					this.SendPropertyChanging();
					this._NgayThi = value;
					this.SendPropertyChanged("NgayThi");
					this.OnNgayThiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GioThi", DbType="Time NOT NULL")]
		public System.TimeSpan GioThi
		{
			get
			{
				return this._GioThi;
			}
			set
			{
				if ((this._GioThi != value))
				{
					this.OnGioThiChanging(value);
					this.SendPropertyChanging();
					this._GioThi = value;
					this.SendPropertyChanged("GioThi");
					this.OnGioThiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GioiHan", DbType="Int NOT NULL")]
		public int GioiHan
		{
			get
			{
				return this._GioiHan;
			}
			set
			{
				if ((this._GioiHan != value))
				{
					this.OnGioiHanChanging(value);
					this.SendPropertyChanging();
					this._GioiHan = value;
					this.SendPropertyChanged("GioiHan");
					this.OnGioiHanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNV", DbType="NChar(10)")]
		public string MaNV
		{
			get
			{
				return this._MaNV;
			}
			set
			{
				if ((this._MaNV != value))
				{
					if (this._NhanVien.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaNVChanging(value);
					this.SendPropertyChanging();
					this._MaNV = value;
					this.SendPropertyChanged("MaNV");
					this.OnMaNVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ThiThu_ChiTietDK_TT", Storage="_ChiTietDK_TTs", ThisKey="MaTT", OtherKey="MaTT")]
		public EntitySet<ChiTietDK_TT> ChiTietDK_TTs
		{
			get
			{
				return this._ChiTietDK_TTs;
			}
			set
			{
				this._ChiTietDK_TTs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ThiThu_KetQua", Storage="_KetQuas", ThisKey="MaTT", OtherKey="MaTT")]
		public EntitySet<KetQua> KetQuas
		{
			get
			{
				return this._KetQuas;
			}
			set
			{
				this._KetQuas.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhanVien_ThiThu", Storage="_NhanVien", ThisKey="MaNV", OtherKey="MaNV", IsForeignKey=true, DeleteRule="SET NULL")]
		public NhanVien NhanVien
		{
			get
			{
				return this._NhanVien.Entity;
			}
			set
			{
				NhanVien previousValue = this._NhanVien.Entity;
				if (((previousValue != value) 
							|| (this._NhanVien.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NhanVien.Entity = null;
						previousValue.ThiThus.Remove(this);
					}
					this._NhanVien.Entity = value;
					if ((value != null))
					{
						value.ThiThus.Add(this);
						this._MaNV = value.MaNV;
					}
					else
					{
						this._MaNV = default(string);
					}
					this.SendPropertyChanged("NhanVien");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ChiTietDK_TTs(ChiTietDK_TT entity)
		{
			this.SendPropertyChanging();
			entity.ThiThu = this;
		}
		
		private void detach_ChiTietDK_TTs(ChiTietDK_TT entity)
		{
			this.SendPropertyChanging();
			entity.ThiThu = null;
		}
		
		private void attach_KetQuas(KetQua entity)
		{
			this.SendPropertyChanging();
			entity.ThiThu = this;
		}
		
		private void detach_KetQuas(KetQua entity)
		{
			this.SendPropertyChanging();
			entity.ThiThu = null;
		}
	}
}
#pragma warning restore 1591
